inherit_gem:
  rubocop-mdsol: rubocop.yml

require:
  - rubocop-performance

AllCops:
  Exclude:
    - gemfiles/**/*

Gemspec/RequireMFA:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - spec/client/authenticator_spec.rb

Lint/MissingSuper:
  Exclude:
    - exe/mauth-client
    - lib/mauth/faraday.rb
    - lib/mauth/rack.rb

Metrics/AbcSize:
  Exclude:
    - lib/mauth/client.rb
    - lib/mauth/client/authenticator.rb
    - lib/mauth/proxy.rb

Metrics/MethodLength:
  Exclude:
    - lib/mauth/client.rb

Metrics/ModuleLength:
  Exclude:
    - lib/mauth/client/authenticator.rb

Naming/FileName:
  Exclude:
    - lib/mauth-client.rb

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Exclude:
    - exe/mauth-client

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
