language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/faraday_0.x.gemfile
  - gemfiles/faraday_1.x.gemfile

before_install:
  - gem update --system --force -N > /dev/null && echo "Rubygems version $(gem --version)"
  - gem install bundler --force -N -v=2.1.4 && bundle --version

install:
  - bundle install --jobs=3 --retry=3
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/mdsol/fossa_ci_scripts/master/travis_ci/fossa_install.sh |
    bash -s -- -b $TRAVIS_BUILD_DIR

script:
  - bundle exec rspec
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/mdsol/fossa_ci_scripts/master/travis_ci/fossa_run.sh |
    bash -s -- -b $TRAVIS_BUILD_DIR

deploy:
  provider: rubygems
  gem: mauth-client
  api_key:
    secure: Y5UXg5u7+fBWAbzdyA8j787Yf55xbkCBEEv1AepeCXP+j5cmvyY6yU+2iVqOXjKdDPXU1U1n+GNfsqx3O9u7hOSYWipEZN2EtWKpxhk5Q5BFYNGgNrX5HjEATiJGdHdWxAtYpmTPOdPk12EFOoMPqR7rfk7xBlarkI+3TWMJiW1ng/cYAzGMnjnmmG98v2fGwb9F096WhJxmzToVel/9AXpBLftz9LKLVlknncob3MlUOfDWol4z6dLfu7ENTEN1orzPfHte1EA4jUEuJoSSzdMqs5zdtlMglicOcfv7jtXApGNpCccfzIlpT3s02JbLmlFsIr6YpLQlrARjhbRyrgUm3p0gomAa5ru+QqBKgfyrtObn6UEoegR/LYQzaR7CLI3kvRGQwNKqHQBtMNGCLJKIpRsjV+5EMcDJS515jjaPadvXMuDj7T5wisV0d91jmebKxR77GSv+NG72GTmbbjoiIW7bwDI32QKzCc55MvibbqZ596G8mZQZOMfx9upU1NDVqNKmtVNtFkfm633sOPEaTELVX8KRg3DznhDOsUmcVhNg3kr5+hTHnlTQwgaXLDUFpm2/UU9JLJFj/H9X2/p9vRnT3O6m0qOAghi3VSjXJRplR78AQSvbBDryHNcbTUhElpbkhV5DKzOXAVpG9hAh36yVHSfO5CF8/0pleL4=
  on:
    tags: true
    repo: mdsol/mauth-client-ruby
    condition: $TRAVIS_RUBY_VERSION == 2.7 && $BUNDLE_GEMFILE == $TRAVIS_BUILD_DIR/gemfiles/faraday_1.x.gemfile
