dist: focal
language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1

env:
  global:
    - BUNDLE_JOBS=4

jobs:
  exclude:
    - rvm: 2.5
      gemfile: gemfiles/faraday_2.x.gemfile
    - rvm: 3.0
      gemfile: gemfiles/faraday_0.x.gemfile # Faraday v0.x does not officially support Ruby 3.0 (see: https://github.com/lostisland/faraday/releases/tag/v1.3.0)
    - rvm: 3.1
      gemfile: gemfiles/faraday_0.x.gemfile # Faraday v0.x does not officially support Ruby 3.0 (see: https://github.com/lostisland/faraday/releases/tag/v1.3.0)

gemfile:
  - gemfiles/faraday_0.x.gemfile
  - gemfiles/faraday_1.x.gemfile
  - gemfiles/faraday_2.x.gemfile

before_install:
  - gem update --system --force -N > /dev/null && echo "Rubygems version $(gem --version)" && bundle --version

install:
  - bundle install
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/mdsol/fossa_ci_scripts/main/travis_ci/fossa_install.sh |
    bash -s -- -b $TRAVIS_BUILD_DIR

script:
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec rake benchmark
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/mdsol/fossa_ci_scripts/main/travis_ci/fossa_run.sh |
    bash -s -- -b $TRAVIS_BUILD_DIR

deploy:
  provider: rubygems
  gem: mauth-client
  api_key:
    secure: QDp0P/lMGLYc4+A3M6VD9y551X6GrGwOSBE6xSG4lE6mPXoSISK5Yj18vNWQRQuQ4BsE6CdfZ/xsPjSRDda6b+yUQbgisjJ+Ry6jUVE1v9UKTZ0VHgHyXcsaJFC29tBKBeuGCj0AD5qhbTO1+ybeZSUfdSeVVoidD4W/bSnvzlT1Lht7IE8jbHbR57LsJKoEaDxKu33dg4CYV96xrlYGxHAS2UgEgi5Ve3ohzBWkX9RWF/wWoGCzIYhJBzXgCEEFw8iWkspjTePgv9yjD2HIMtF44aiSTHM5iqBBsYJ7A8+kUwoq7+srsashHZ1wZz1YulsCSkjwM9AXZ4E0f9AnERw/RQ5gG7bCuHZtSG9g/0SWBQeNfkAF3An6eTSS24KVfnarGdH2bk0G28k2oP26MWiDKz8nlQxNAY4rH+dITael18bgf45H4KccQqiooBEGnuYpUAuIPB+1l+BsIcRQnrU3LDtmtZn0KrCHHJ7EHOdogOG+/Pxof8ht1xF7V+HYhhzSRJs2JkvmZsp4q2T7W6b6kfi59Cz3LpqA1HHYcL5/OFZeLA/TlCNke0CRMxG8k3udDKj50jqFATXEa8lNyGLjmWh7tL9Bb/uy+CU47qUdx+V4K+kheAvNFtHfpxmyUGJSY0FH02H1VBPWm10DZ7kH+6jgCKyXuql+yWDw62s=
  on:
    tags: true
    repo: mdsol/mauth-client-ruby
    condition: $TRAVIS_RUBY_VERSION == 3.1 && $BUNDLE_GEMFILE == $TRAVIS_BUILD_DIR/gemfiles/faraday_1.x.gemfile
