development:
  mauth_baseurl: https://mauth.imedidata.com
  mauth_api_version: v1
  app_uuid: NORMAL-DEVELOPMENT
production:
  mauth_baseurl: https://mauth.imedidata.com
  mauth_api_version: v1
  app_uuid: NORMAL-PRODUCTION
