common:
  mauth_baseurl: http://localhost:4567
  mauth_api_version: v1
  app_uuid: 00000000-0000-0000-0000-000000000000
  private_key_file: config/mauth_key

development:
  mauth_baseurl: http://localhost:4567
  mauth_api_version: v1
  app_uuid: 00000000-0000-0000-0000-000000000000
  private_key_file: config/mauth_key

